---
lighthouse_install_dir: "/opt/lighthouse"
lighthouse_user: "lighthouse"
lighthouse_group: "lighthouse"
lighthouse_data_dir: "/var/lib/lighthouse"
lighthouse_pgp_key: "15E66D941F697E28F49381F426416DC3F30674B0"
lighthouse_download_base: "https://github.com/sigp/lighthouse/releases/download/{{ lighthouse_version }}"
